from __future__ import annotations

import asyncio
import logging
import os
import smtplib
from email.message import EmailMessage
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class EmailNotificationService:
    @staticmethod
    def get_config() -> Dict[str, Any]:
        return {
            "smtp_host": os.getenv("SMTP_HOST", "smtp.gmail.com"),
            "smtp_port": int(os.getenv("SMTP_PORT", "587")),
            "smtp_user": os.getenv("SMTP_USER", ""),
            "smtp_password": os.getenv("SMTP_PASSWORD", ""),
            "smtp_tls": os.getenv("SMTP_TLS", "true").lower() == "true",
            "from_address": os.getenv("SMTP_FROM", "alerts@cyberguard.ai"),
        }

    @staticmethod
    def build_html_template(subject: str, body: str, title: str = "CyberGuard AI") -> str:
        return f"""
        <html><body style='font-family:Arial,sans-serif;background:#07111f;padding:24px;color:#e2e8f0;'><div style='max-width:640px;margin:auto;background:#0f172a;border:1px solid #1e293b;border-radius:12px;padding:24px;'>
        <h2 style='margin-top:0;color:#ff8c42;'>{title}</h2>
        <h3 style='margin-bottom:8px;'>{subject}</h3>
        <p>{body}</p>
        <p style='color:#94a3b8;font-size:12px;'>This notification was generated by CyberGuard AI.</p>
        </div></body></html>
        """

    @staticmethod
    async def send_email(to_addresses: List[str], subject: str, body: str, html_body: Optional[str] = None) -> Dict[str, bool]:
        config = EmailNotificationService.get_config()
        if not config["smtp_user"] or not config["smtp_password"]:
            logger.warning("SMTP credentials are not configured; skipping email delivery")
            return {addr: False for addr in to_addresses}

        message = EmailMessage()
        message["Subject"] = subject
        message["From"] = config["from_address"]
        message["To"] = ", ".join(to_addresses)
        message.set_content(body)
        if html_body:
            message.add_alternative(html_body, subtype="html")

        try:
            with smtplib.SMTP(config["smtp_host"], config["smtp_port"], timeout=20) as smtp:
                if config["smtp_tls"]:
                    smtp.starttls()
                smtp.login(config["smtp_user"], config["smtp_password"])
                smtp.send_message(message)
            logger.info("Email notification delivered", extra={"recipients": to_addresses})
            return {addr: True for addr in to_addresses}
        except Exception as exc:
            logger.exception("Email notification failed: %s", exc)
            return {addr: False for addr in to_addresses}
